services:
  postgres:
    image: postgres:16
    container_name: tasks-postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 2s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate:v4.16.2
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate"]
    command:
      - "-path=/migrations"
      - "-database=postgres://user:pass@postgres:5432/db?sslmode=disable"
      - "up"
    restart: on-failure

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.11
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --rpc-addr
      - redpanda:33145
      - --advertise-rpc-addr
      - redpanda:33145
      - --mode
      - dev-container
      - --smp
      - "1"
      - --default-log-level=info
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.11
    depends_on:
      - redpanda
    entrypoint:
      - /bin/sh
      - -ec
      - |
        until rpk cluster info -X brokers=redpanda:9092; do
          echo "waiting for redpanda..."
          sleep 2
        done
        rpk topic create jobs -p 3 -r 1 --if-not-exists -X brokers=redpanda:9092
        echo "topics created"

  api:
    build:
      context: .
      dockerfile: ./internal/config/Dockerfile
    container_name: api
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      topic-init:
        condition: service_completed_successfully
      migrate:
        condition: service_completed_successfully
    command: ["/bin/api"]
    ports:
      - "8080:8080"
    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: ./internal/config/Dockerfile
    container_name: consumer
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      topic-init:
        condition: service_completed_successfully
      migrate:
        condition: service_completed_successfully
    command: ["/bin/consumer"]
    ports:
      - "8082:8082"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: ./internal/config/Dockerfile
    container_name: worker
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      topic-init:
        condition: service_completed_successfully
      migrate:
        condition: service_completed_successfully
    command: [ "/bin/worker" ]
    ports:
      - "8081:8081"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    depends_on:
      - api
    ports:
      - "9090:9090"
    volumes:
      - ./internal/config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle

volumes:
  pg_data:
    name: pg_data
  redpanda_data:
  prometheus_data: