services:
  postgres:
    image: postgres:16
    container_name: tasks-postgres
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    volumes:
      - pg_data_tasks:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tasks"]
      interval: 2s
      timeout: 5s
      retries: 10

  migrate-tasks:
    image: migrate/migrate:v4.16.2
    container_name: migrate-tasks
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate"]
    command:
      - "-path=/migrations/tasks/"
      - "-database=postgres://user:pass@postgres:5432/tasks?sslmode=disable"
      - "up"
    restart: on-failure

  postgres-users-consumer:
    image: postgres:16
    container_name: postgres-users-consumer
    environment:
      POSTGRES_DB: users-consumer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5433:5432"
    volumes:
      - pg_data_users_consumer:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d users-consumer" ]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: on-failure

  postgres-users-producer:
    image: postgres:16
    container_name: postgres-users-producer
    environment:
      POSTGRES_DB: users-producer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5434:5432"
    volumes:
      - pg_data_users_producer:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d users-producer" ]
      interval: 2s
      timeout: 5s
      retries: 10

  migrate-users:
    image: migrate/migrate:v4.16.2
    container_name: migrate-users
    depends_on:
      postgres-users-consumer:
        condition: service_healthy
      postgres-users-producer:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint:
      - /bin/sh
      - -ec
      - |
        migrate -path=/migrations/users \
          -database="postgres://user:pass@postgres-users-producer:5432/users-producer?sslmode=disable" up

        migrate -path=/migrations/users \
          -database="postgres://user:pass@postgres-users-consumer:5432/users-consumer?sslmode=disable" up
    restart: on-failure

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.11
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --rpc-addr
      - redpanda:33145
      - --advertise-rpc-addr
      - redpanda:33145
      - --mode
      - dev-container
      - --smp
      - "1"
      - --default-log-level=info
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  users-broker:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.11
    container_name: users-broker
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19093
      - --advertise-kafka-addr
      - internal://users-broker:9092,external://localhost:19093
      - --rpc-addr
      - users-broker:33145
      - --advertise-rpc-addr
      - users-broker:33145
      - --mode
      - dev-container
      - --smp
      - "1"
      - --default-log-level=info
    ports:
      - "19093:19093"
      - "29644:9644"
    volumes:
      - users_broker_data:/var/lib/redpanda/data

  topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.11
    depends_on:
      - redpanda
    entrypoint:
      - /bin/sh
      - -ec
      - |
        until rpk cluster info -X brokers=redpanda:9092; do
          echo "waiting for redpanda..."
          sleep 2
        done
        rpk topic create jobs -p 3 -r 1 --if-not-exists -X brokers=redpanda:9092
        echo "topics created"

  users-topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.11
    depends_on:
      - users-broker
    entrypoint:
      - /bin/sh
      - -ec
      - |
        until rpk cluster info -X brokers=users-broker:9092; do
          echo "waiting for users-broker..."
          sleep 2
        done
        rpk topic create users -p 3 -r 1 --if-not-exists -X brokers=users-broker:9092
        echo "topics created"

  api:
    build:
      context: .
      dockerfile: ./internal/config/Dockerfile
    container_name: tasks
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      topic-init:
        condition: service_completed_successfully
      migrate-tasks:
        condition: service_completed_successfully
    command: ["/bin/tasks"]
    ports:
      - "8080:8080"
    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: ./internal/config/Dockerfile
    container_name: consumer
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      topic-init:
        condition: service_completed_successfully
      migrate-tasks:
        condition: service_completed_successfully
    command: ["/bin/consumer"]
    ports:
      - "8082:8082"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: ./internal/config/Dockerfile
    container_name: worker
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      topic-init:
        condition: service_completed_successfully
      migrate-tasks:
        condition: service_completed_successfully
    command: [ "/bin/worker" ]
    ports:
      - "8081:8081"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    depends_on:
      - api
    ports:
      - "9090:9090"
    volumes:
      - ./internal/config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  pg_data_tasks:
  pg_data_users_consumer:
  pg_data_users_producer:
  redpanda_data:
  users_broker_data:
  prometheus_data:
  grafana_data: